spring.application.name=demo

# Server
server.port=8080

# API Configuration
api.prefix=/api/v1

# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/library-management?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=0134
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Logging
logging.level.root=INFO
logging.level.com.yourproject=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/demo.log

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration